create database HEALTH_HISTORY_REPORT
go
USE HEALTH_HISTORY_REPORT
go
CREATE TABLE TYPE (TypeID int PRIMARY KEY ,  TypeName varchar(50))
go
create table PET (PetID int primary key, PetName varchar(50), age int,OWNERID INT foreign key references [OWNER](OWNERID), TYPEID INT FOREIGN KEY REFERENCES TYPE (TYPEID))
go
CREATE TABLE [OWNER] (OWNERID INT PRIMARY KEY, OWNERNAME VARCHAR(50), ADDRESS VARCHAR(50))
go
CREATE TABLE [PROCEDURE] (PROID INT PRIMARY KEY, PRONAME VARCHAR(50), PRICE DECIMAL)
go
create table INVOICE
(
   INVOICEID int primary key,
   INVOICEDATE DATE,
   OWNERID INT FOREIGN KEY REFERENCES  [OWNER](OWNERID)
)
CREATE TABLE INVOICEDETAIL
(
   ID INT,
   ProID INT FOREIGN KEY REFERENCES  [PROCEDURE](PROID),
   PetID  INT FOREIGN KEY REFERENCES  PET(PetID),
   PRIMARY KEY(ID, ProID,PetID )
)